// Derive chessground inputs from the backend's legal move list (UCI). No rules here:
// every list entry was generated by the backend for the current position.

import type { Key } from 'chessground/types'

const isDrop = (uci: string) => uci[1] === '@'

/** Board move destinations (drops excluded), keyed by origin square. */
export function boardDests(legal: string[]): Map<Key, Key[]> {
  const dests = new Map<Key, Key[]>()
  for (const uci of legal) {
    if (isDrop(uci)) continue
    const from = uci.slice(0, 2) as Key
    const to = uci.slice(2, 4) as Key
    const list = dests.get(from) ?? []
    if (!list.includes(to)) list.push(to)
    dests.set(from, list)
  }
  return dests
}

/** Squares where the piece `letter` (P N B R Q) may legally be dropped. */
export function dropSquares(legal: string[], letter: string): Key[] {
  const prefix = `${letter.toUpperCase()}@`
  return legal.filter((uci) => uci.startsWith(prefix)).map((uci) => uci.slice(2, 4) as Key)
}

/** Promotion piece letters available for orig->dest (empty if the move is not a promotion). */
export function promotionChoices(legal: string[], orig: string, dest: string): string[] {
  const prefix = orig + dest
  return legal.filter((uci) => uci.length === 5 && uci.startsWith(prefix)).map((uci) => uci[4].toUpperCase())
}
